/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is up */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a receipt JPG and start async extraction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": components["schemas"]["UploadReceiptForm"];
                };
            };
            responses: {
                /** @description Job submitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobUploadResponse"];
                    };
                };
                /** @description Missing or invalid image */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll job status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current job status */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobStatusResponse"];
                    };
                };
                /** @description Job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream for job progress
         * @description Emits `processing`, `done`, or `error` events. Connection closes after terminal event.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description SSE stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description Job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List receipts with optional filters */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                    category?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Receipts ordered by date desc */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Receipt"][];
                    };
                };
                /** @description Invalid query parameter (e.g. malformed date, non-numeric limit) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipt/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one receipt with line items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Receipt detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReceiptWithItems"];
                    };
                };
                /** @description Receipt not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a receipt (cascades to line items) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteReceiptResponse"];
                    };
                };
                /** @description Receipt not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/receipt/{id}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Serve the original receipt image file */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JPEG image bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": string;
                    };
                };
                /** @description Image not found on disk or in DB */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Spending summary grouped by category */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description One row per category, ordered by total_spent desc */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpendingSummary"];
                    };
                };
                /** @description Invalid query parameter (e.g. malformed date) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Free-form question answered by Claude over your receipts */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AskRequest"];
                };
            };
            responses: {
                /** @description Claude's answer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AskResponse"];
                    };
                };
                /** @description Missing or invalid `question` field */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationErrorResponse"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example Not found */
            error: string;
        };
        ValidationErrorResponse: {
            /** @enum {string} */
            error: "Invalid request";
            issues: {
                /** @example limit */
                path: string;
                /** @example Expected number, received string */
                message: string;
            }[];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
            /** @example receipt-assistant */
            service: string;
            /** @example 1.0.0 */
            version: string;
        };
        ExtractionMeta: {
            quality: {
                confidence_score: number;
                missing_fields: string[];
                warnings: string[];
            };
            business: {
                is_reimbursable: boolean;
                is_tax_deductible: boolean;
                is_recurring: boolean;
                is_split_bill: boolean;
            };
        } | null;
        Receipt: {
            id: string;
            merchant: string;
            /**
             * @description ISO date YYYY-MM-DD
             * @example 2026-04-19
             */
            date: string;
            total: number;
            currency?: string | null;
            category?: string | null;
            payment_method?: string | null;
            tax?: number | null;
            tip?: number | null;
            notes?: string | null;
            raw_text?: string | null;
            image_path?: string | null;
            address?: string | null;
            latitude?: number | null;
            longitude?: number | null;
            place_id?: string | null;
            /** @enum {string} */
            status?: "processing" | "done" | "error";
            extraction_meta?: components["schemas"]["ExtractionMeta"];
            created_at?: string;
            updated_at?: string;
        };
        ReceiptItem: {
            name: string;
            quantity?: number | null;
            unit_price?: number | null;
            total_price?: number | null;
            category?: string | null;
        };
        ReceiptWithItems: components["schemas"]["Receipt"] & {
            items: components["schemas"]["ReceiptItem"][];
        };
        JobUploadResponse: {
            jobId: string;
            receiptId: string;
            /** @enum {string} */
            status: "processing";
            /** @example /jobs/abc/stream */
            stream: string;
            /** @example /jobs/abc */
            poll: string;
        };
        /** @enum {string} */
        JobStatus: "queued" | "processing" | "done" | "error";
        JobStatusResponse: {
            jobId: string;
            receiptId: string;
            status: components["schemas"]["JobStatus"];
            error: string | null;
        };
        SpendingSummaryItem: {
            category: string | null;
            count: number;
            total_spent: number;
            avg_per_receipt: number;
        };
        SpendingSummary: components["schemas"]["SpendingSummaryItem"][];
        AskRequest: {
            /** @example How much did I spend on groceries last month? */
            question: string;
        };
        AskResponse: {
            answer: string;
        };
        UploadReceiptForm: {
            /** Format: binary */
            image: string;
            notes?: string;
        };
        DeleteReceiptResponse: {
            /** @enum {boolean} */
            success: true;
            id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
