/**
 * What each document on a transaction IS, how the documents order, and
 * what to call them — derived from `kind` + `mime_type` + `source_meta`,
 * which is everything `TransactionDocumentRef` carries
 * (api-types.ts:5001-5014: no `created_at`, no `file_path`, no `sha256`).
 *
 * A transaction can carry 2-4 documents and until #165 only one of them
 * was ever rendered, so this module is the single place that decides
 * which leads and what each is called.
 *
 * Pure by design: no React, no fetching, no cache reads.
 */
import type { BackendTransaction } from './api';

/** One element of `Transaction.documents` — the slim
 *  `TransactionDocumentRef` projection, NOT the full `Document`. */
export type DocumentRef = BackendTransaction['documents'][number];

export type DocumentRole =
  /** A photographed or scanned paper receipt. */
  | 'photo'
  /** A portal invoice / saved web confirmation — the itemized artifact. */
  | 'itemization'
  /** A receipt PDF. */
  | 'receipt'
  /** The message the receipt arrived in, not the receipt itself. */
  | 'email'
  /** A periodic statement that merely CONTAINS this line. */
  | 'statement'
  | 'other';

/**
 * Lower sorts first: most itemized at the top (#165 C).
 *
 * `photo` leads deliberately. That is also `primaryDocument()`'s own
 * preference (core.ts:442-446 picks `documents.find(d => d.kind ===
 * 'receipt_image')` first), so on the common photo receipt the
 * top-listed row and `receipt.documentId` name the same document and no
 * new divergence between "what is on top" and "what the actions target"
 * is introduced.
 *
 * `statement` is last among live documents: a period statement is the
 * least itemized artifact that can be attached to a single purchase.
 */
const ROLE_RANK: Record<DocumentRole, number> = {
  photo: 0,
  itemization: 1,
  receipt: 2,
  email: 3,
  statement: 4,
  other: 5,
};

/**
 * Row title. `photo` and `receipt` share a noun on purpose — the format
 * tag (JPEG vs PDF) is what tells them apart, and inventing two words
 * for "the receipt" would read as two different kinds of thing.
 *
 * 'Invoice' for `itemization` is an INFERENCE: nothing in the payload
 * says "invoice" (an HTML invoice arrives with `kind: 'receipt_pdf'` —
 * #137). Backend #240's `role` column is what will make it a fact; when
 * it lands this table is read by role and the wording stops being a
 * guess.
 */
const ROLE_TITLE: Record<DocumentRole, string> = {
  photo: 'Receipt',
  itemization: 'Invoice',
  receipt: 'Receipt',
  email: 'Email',
  statement: 'Statement',
  other: 'Document',
};

/**
 * Base mime with the charset param stripped and lowercased, so
 * `text/html; charset=utf-8` matches.
 *
 * DocumentBody.tsx keeps its own copy of this two-line parse rather than
 * importing this one. That is deliberate: that parse is the #137
 * containment gate deciding sandboxed-/rendered vs unsandboxed
 * -/content, and it should not be changeable from a labelling module.
 */
export function baseMimeType(mime: string | null | undefined): string {
  return (mime ?? '').split(';')[0]?.trim().toLowerCase() ?? '';
}

/**
 * Inferred role. Precedence mirrors the VIEWER's branch order
 * (email > html > pdf > image) so the label and the renderer never
 * disagree about what a document is.
 *
 * `kind` alone is not enough: #137 records that an HTML invoice arrives
 * with `kind: 'receipt_pdf'`, which is why mime decides the itemization
 * call. Symmetrically an `.eml` is recognized by `message/rfc822` as
 * well as by `kind`, so an email filed under a different kind does not
 * fall through to 'other'.
 */
function inferRole(d: DocumentRef): DocumentRole {
  const base = baseMimeType(d.mime_type);
  if (d.kind === 'receipt_email' || base === 'message/rfc822') return 'email';
  if (base === 'text/html' || base === 'application/xhtml+xml') return 'itemization';
  if (d.kind === 'statement_pdf') return 'statement';
  if (d.kind === 'receipt_image' || base.startsWith('image/')) return 'photo';
  if (d.kind === 'receipt_pdf' || base === 'application/pdf') return 'receipt';
  return 'other';
}

/** Backend #240 spellings → this module's vocabulary. */
const DECLARED_ROLES: Record<string, DocumentRole> = {
  itemization: 'itemization',
  invoice: 'itemization',
  itemized_receipt: 'itemization',
  receipt: 'receipt',
  receipt_photo: 'photo',
  photo: 'photo',
  email: 'email',
  email_receipt: 'email',
  payment_confirmation: 'email',
  statement: 'statement',
  statement_line: 'statement',
  other: 'other',
};

/**
 * THE #240 SEAM.
 *
 * `role` is not in api-types.ts yet — that file is generated by
 * `npm run api:types` from the backend's OpenAPI spec — so it is read
 * through a narrow cast HERE and nowhere else in the app. Both
 * `compareDocuments` and `toDocumentEntries` go through this one
 * function, so the column lands in one place.
 *
 * When #240 ships: regenerate the types, drop the cast, add any new
 * spelling to DECLARED_ROLES (and, if the vocabulary genuinely grows, a
 * member to DocumentRole plus one line each in ROLE_RANK and
 * ROLE_TITLE). Inference deliberately STAYS as the fallback rather than
 * being deleted — rows the backfill misses would otherwise all collapse
 * onto one role, and an unrecognised declared role would produce an
 * undefined rank.
 */
export function documentRole(d: DocumentRef): DocumentRole {
  const declared = (d as { role?: string | null }).role;
  if (typeof declared === 'string' && DECLARED_ROLES[declared]) {
    return DECLARED_ROLES[declared];
  }
  return inferRole(d);
}

/**
 * Mono micro-caps format tag. Separates two rows that share a title (a
 * photo next to an HTML invoice; two photos) without depending on
 * `source_meta` being populated. Mime first — the more specific fact —
 * with `kind` only as the fallback when mime is absent. Returns '' when
 * the format is genuinely unknowable, so the caller renders nothing
 * rather than a blank pill.
 */
export function formatTag(d: DocumentRef): string {
  const base = baseMimeType(d.mime_type);
  if (base === 'message/rfc822') return 'EML';
  if (base === 'text/html' || base === 'application/xhtml+xml') return 'HTML';
  if (base === 'application/pdf') return 'PDF';
  if (base.startsWith('image/')) return base.slice('image/'.length).toUpperCase();
  if (d.kind === 'receipt_image') return 'IMAGE';
  if (d.kind === 'receipt_pdf' || d.kind === 'statement_pdf') return 'PDF';
  if (d.kind === 'receipt_email') return 'EMAIL';
  return '';
}

/** `source_meta` values are `unknown`. Accept only a non-empty string —
 *  the pre-existing `as string | undefined` casts would let a number
 *  reach JSX (and an object throw at render). */
function metaString(meta: DocumentRef['source_meta'], key: string): string | null {
  const v = meta?.[key];
  return typeof v === 'string' && v.trim() !== '' ? v.trim() : null;
}

/**
 * Total order — never array order. The backend promises no ordering for
 * `Transaction.documents`, so two loads of the same transaction could
 * otherwise disagree about which document leads.
 */
export function compareDocuments(a: DocumentRef, b: DocumentRef): number {
  // 1. Live before deleted. A tombstoned document is still listed
  //    (#165 G) but must never push the live invoice down.
  const da = a.deleted_at == null ? 0 : 1;
  const db = b.deleted_at == null ? 0 : 1;
  if (da !== db) return da - db;

  // 2. Most itemized first (#165 C).
  const ra = ROLE_RANK[documentRole(a)];
  const rb = ROLE_RANK[documentRole(b)];
  if (ra !== rb) return ra - rb;

  // 3. Stable tiebreak. TransactionDocumentRef carries no `created_at`
  //    and no `file_path`, so there is no chronology and no filename to
  //    sort by; the row id is the only key that is unique and identical
  //    on every load and every device. Plain `<`/`>` rather than
  //    localeCompare, which is locale-dependent and so not
  //    deterministic across users.
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

export interface DocumentEntry {
  /** The raw ref, carried through so the viewer keeps deciding on THIS
   *  document's own `kind` / `mime_type` / `source_meta` (#165 E). */
  doc: DocumentRef;
  role: DocumentRole;
  /** Row title — the noun. */
  title: string;
  /** Mono micro-caps format tag; '' when unknowable. */
  format: string;
  /** One line of provenance (email subject, else sender), or null. */
  subtitle: string | null;
}

/**
 * Ordered, labelled entries for one transaction's documents.
 *
 * `[...docs]` is load-bearing and must not be "optimized" away:
 * `receipt.documents` IS the react-query cache's own array (core.ts:631
 * passes `t.documents` through verbatim) and `Array.prototype.sort`
 * mutates in place. Never `docs.sort(...)`.
 */
export function toDocumentEntries(docs: readonly DocumentRef[]): DocumentEntry[] {
  const entries = [...docs].sort(compareDocuments).map((doc) => {
    const role = documentRole(doc);
    return {
      doc,
      role,
      title: ROLE_TITLE[role],
      format: formatTag(doc),
      subtitle:
        metaString(doc.source_meta, 'subject') ?? metaString(doc.source_meta, 'sender'),
    };
  });

  // Two rows can still read identically — two photos, two EMLs with no
  // subject. Disambiguate ONLY those, so the ordinary case keeps the
  // plain noun: a twin that already has a subtitle is distinguishable
  // as it stands; one without gets a 1-based ordinal.
  return entries.map((e, i) => {
    if (e.subtitle) return e;
    const twin = entries.some(
      (o, j) => j !== i && o.title === e.title && o.format === e.format,
    );
    return twin ? { ...e, title: `${e.title} ${i + 1}` } : e;
  });
}

// Production check — transaction c01d0048-3409-4918-9af2-18bf4a6da983,
// whose payload array order is [email, html] (verified live):
//   {receipt_pdf,   text/html,      source_meta: null}
//     -> role 'itemization', rank 1 -> { title: 'Invoice', format: 'HTML',
//        subtitle: null }                                   LISTED FIRST
//   {receipt_email, message/rfc822, subject: 'Confirmation of your Zelle® payment'}
//     -> role 'email', rank 3 -> { title: 'Email', format: 'EML',
//        subtitle: 'Confirmation of your Zelle® payment' }  LISTED SECOND
// i.e. the itemized invoice above the payment confirmation, which is
// the document the owner actually wants and the opposite of today.
