/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AddRouteImport } from './routes/add'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellTransactionsRouteImport } from './routes/_shell/transactions'
import { Route as ShellWishIndexRouteImport } from './routes/_shell/wish/index'
import { Route as ShellSettingsIndexRouteImport } from './routes/_shell/settings/index'
import { Route as ShellOwnedIndexRouteImport } from './routes/_shell/owned/index'
import { Route as ShellInsightsIndexRouteImport } from './routes/_shell/insights/index'
import { Route as ShellBatchesIndexRouteImport } from './routes/_shell/batches/index'
import { Route as ShellWishWishIdRouteImport } from './routes/_shell/wish/$wishId'
import { Route as ShellReviewYearlyRouteImport } from './routes/_shell/review/yearly'
import { Route as ShellReviewMonthlyRouteImport } from './routes/_shell/review/monthly'
import { Route as ShellReceiptReceiptIdRouteImport } from './routes/_shell/receipt/$receiptId'
import { Route as ShellOwnedOwnedItemIdRouteImport } from './routes/_shell/owned/$ownedItemId'
import { Route as ShellMerchantMerchantIdRouteImport } from './routes/_shell/merchant/$merchantId'
import { Route as ShellBrandBrandIdRouteImport } from './routes/_shell/brand/$brandId'
import { Route as ShellBatchesBatchIdRouteImport } from './routes/_shell/batches/$batchId'
import { Route as ShellSettingsProductsIndexRouteImport } from './routes/_shell/settings/products/index'
import { Route as ShellSettingsBrandsIndexRouteImport } from './routes/_shell/settings/brands/index'

const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTransactionsRoute = ShellTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWishIndexRoute = ShellWishIndexRouteImport.update({
  id: '/wish/',
  path: '/wish/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsIndexRoute = ShellSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnedIndexRoute = ShellOwnedIndexRouteImport.update({
  id: '/owned/',
  path: '/owned/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellInsightsIndexRoute = ShellInsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBatchesIndexRoute = ShellBatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWishWishIdRoute = ShellWishWishIdRouteImport.update({
  id: '/wish/$wishId',
  path: '/wish/$wishId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReviewYearlyRoute = ShellReviewYearlyRouteImport.update({
  id: '/review/yearly',
  path: '/review/yearly',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReviewMonthlyRoute = ShellReviewMonthlyRouteImport.update({
  id: '/review/monthly',
  path: '/review/monthly',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReceiptReceiptIdRoute = ShellReceiptReceiptIdRouteImport.update({
  id: '/receipt/$receiptId',
  path: '/receipt/$receiptId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOwnedOwnedItemIdRoute = ShellOwnedOwnedItemIdRouteImport.update({
  id: '/owned/$ownedItemId',
  path: '/owned/$ownedItemId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMerchantMerchantIdRoute = ShellMerchantMerchantIdRouteImport.update({
  id: '/merchant/$merchantId',
  path: '/merchant/$merchantId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBrandBrandIdRoute = ShellBrandBrandIdRouteImport.update({
  id: '/brand/$brandId',
  path: '/brand/$brandId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBatchesBatchIdRoute = ShellBatchesBatchIdRouteImport.update({
  id: '/batches/$batchId',
  path: '/batches/$batchId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsProductsIndexRoute =
  ShellSettingsProductsIndexRouteImport.update({
    id: '/settings/products/',
    path: '/settings/products/',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellSettingsBrandsIndexRoute =
  ShellSettingsBrandsIndexRouteImport.update({
    id: '/settings/brands/',
    path: '/settings/brands/',
    getParentRoute: () => ShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/add': typeof AddRoute
  '/transactions': typeof ShellTransactionsRoute
  '/batches/$batchId': typeof ShellBatchesBatchIdRoute
  '/brand/$brandId': typeof ShellBrandBrandIdRoute
  '/merchant/$merchantId': typeof ShellMerchantMerchantIdRoute
  '/owned/$ownedItemId': typeof ShellOwnedOwnedItemIdRoute
  '/receipt/$receiptId': typeof ShellReceiptReceiptIdRoute
  '/review/monthly': typeof ShellReviewMonthlyRoute
  '/review/yearly': typeof ShellReviewYearlyRoute
  '/wish/$wishId': typeof ShellWishWishIdRoute
  '/batches/': typeof ShellBatchesIndexRoute
  '/insights/': typeof ShellInsightsIndexRoute
  '/owned/': typeof ShellOwnedIndexRoute
  '/settings/': typeof ShellSettingsIndexRoute
  '/wish/': typeof ShellWishIndexRoute
  '/settings/brands/': typeof ShellSettingsBrandsIndexRoute
  '/settings/products/': typeof ShellSettingsProductsIndexRoute
}
export interface FileRoutesByTo {
  '/add': typeof AddRoute
  '/transactions': typeof ShellTransactionsRoute
  '/': typeof ShellIndexRoute
  '/batches/$batchId': typeof ShellBatchesBatchIdRoute
  '/brand/$brandId': typeof ShellBrandBrandIdRoute
  '/merchant/$merchantId': typeof ShellMerchantMerchantIdRoute
  '/owned/$ownedItemId': typeof ShellOwnedOwnedItemIdRoute
  '/receipt/$receiptId': typeof ShellReceiptReceiptIdRoute
  '/review/monthly': typeof ShellReviewMonthlyRoute
  '/review/yearly': typeof ShellReviewYearlyRoute
  '/wish/$wishId': typeof ShellWishWishIdRoute
  '/batches': typeof ShellBatchesIndexRoute
  '/insights': typeof ShellInsightsIndexRoute
  '/owned': typeof ShellOwnedIndexRoute
  '/settings': typeof ShellSettingsIndexRoute
  '/wish': typeof ShellWishIndexRoute
  '/settings/brands': typeof ShellSettingsBrandsIndexRoute
  '/settings/products': typeof ShellSettingsProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/add': typeof AddRoute
  '/_shell/transactions': typeof ShellTransactionsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/batches/$batchId': typeof ShellBatchesBatchIdRoute
  '/_shell/brand/$brandId': typeof ShellBrandBrandIdRoute
  '/_shell/merchant/$merchantId': typeof ShellMerchantMerchantIdRoute
  '/_shell/owned/$ownedItemId': typeof ShellOwnedOwnedItemIdRoute
  '/_shell/receipt/$receiptId': typeof ShellReceiptReceiptIdRoute
  '/_shell/review/monthly': typeof ShellReviewMonthlyRoute
  '/_shell/review/yearly': typeof ShellReviewYearlyRoute
  '/_shell/wish/$wishId': typeof ShellWishWishIdRoute
  '/_shell/batches/': typeof ShellBatchesIndexRoute
  '/_shell/insights/': typeof ShellInsightsIndexRoute
  '/_shell/owned/': typeof ShellOwnedIndexRoute
  '/_shell/settings/': typeof ShellSettingsIndexRoute
  '/_shell/wish/': typeof ShellWishIndexRoute
  '/_shell/settings/brands/': typeof ShellSettingsBrandsIndexRoute
  '/_shell/settings/products/': typeof ShellSettingsProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/transactions'
    | '/batches/$batchId'
    | '/brand/$brandId'
    | '/merchant/$merchantId'
    | '/owned/$ownedItemId'
    | '/receipt/$receiptId'
    | '/review/monthly'
    | '/review/yearly'
    | '/wish/$wishId'
    | '/batches/'
    | '/insights/'
    | '/owned/'
    | '/settings/'
    | '/wish/'
    | '/settings/brands/'
    | '/settings/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/add'
    | '/transactions'
    | '/'
    | '/batches/$batchId'
    | '/brand/$brandId'
    | '/merchant/$merchantId'
    | '/owned/$ownedItemId'
    | '/receipt/$receiptId'
    | '/review/monthly'
    | '/review/yearly'
    | '/wish/$wishId'
    | '/batches'
    | '/insights'
    | '/owned'
    | '/settings'
    | '/wish'
    | '/settings/brands'
    | '/settings/products'
  id:
    | '__root__'
    | '/_shell'
    | '/add'
    | '/_shell/transactions'
    | '/_shell/'
    | '/_shell/batches/$batchId'
    | '/_shell/brand/$brandId'
    | '/_shell/merchant/$merchantId'
    | '/_shell/owned/$ownedItemId'
    | '/_shell/receipt/$receiptId'
    | '/_shell/review/monthly'
    | '/_shell/review/yearly'
    | '/_shell/wish/$wishId'
    | '/_shell/batches/'
    | '/_shell/insights/'
    | '/_shell/owned/'
    | '/_shell/settings/'
    | '/_shell/wish/'
    | '/_shell/settings/brands/'
    | '/_shell/settings/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AddRoute: typeof AddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/transactions': {
      id: '/_shell/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof ShellTransactionsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/wish/': {
      id: '/_shell/wish/'
      path: '/wish'
      fullPath: '/wish/'
      preLoaderRoute: typeof ShellWishIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/': {
      id: '/_shell/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ShellSettingsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owned/': {
      id: '/_shell/owned/'
      path: '/owned'
      fullPath: '/owned/'
      preLoaderRoute: typeof ShellOwnedIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/insights/': {
      id: '/_shell/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof ShellInsightsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/batches/': {
      id: '/_shell/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof ShellBatchesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/wish/$wishId': {
      id: '/_shell/wish/$wishId'
      path: '/wish/$wishId'
      fullPath: '/wish/$wishId'
      preLoaderRoute: typeof ShellWishWishIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/review/yearly': {
      id: '/_shell/review/yearly'
      path: '/review/yearly'
      fullPath: '/review/yearly'
      preLoaderRoute: typeof ShellReviewYearlyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/review/monthly': {
      id: '/_shell/review/monthly'
      path: '/review/monthly'
      fullPath: '/review/monthly'
      preLoaderRoute: typeof ShellReviewMonthlyRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/receipt/$receiptId': {
      id: '/_shell/receipt/$receiptId'
      path: '/receipt/$receiptId'
      fullPath: '/receipt/$receiptId'
      preLoaderRoute: typeof ShellReceiptReceiptIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/owned/$ownedItemId': {
      id: '/_shell/owned/$ownedItemId'
      path: '/owned/$ownedItemId'
      fullPath: '/owned/$ownedItemId'
      preLoaderRoute: typeof ShellOwnedOwnedItemIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/merchant/$merchantId': {
      id: '/_shell/merchant/$merchantId'
      path: '/merchant/$merchantId'
      fullPath: '/merchant/$merchantId'
      preLoaderRoute: typeof ShellMerchantMerchantIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/brand/$brandId': {
      id: '/_shell/brand/$brandId'
      path: '/brand/$brandId'
      fullPath: '/brand/$brandId'
      preLoaderRoute: typeof ShellBrandBrandIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/batches/$batchId': {
      id: '/_shell/batches/$batchId'
      path: '/batches/$batchId'
      fullPath: '/batches/$batchId'
      preLoaderRoute: typeof ShellBatchesBatchIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/products/': {
      id: '/_shell/settings/products/'
      path: '/settings/products'
      fullPath: '/settings/products/'
      preLoaderRoute: typeof ShellSettingsProductsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/brands/': {
      id: '/_shell/settings/brands/'
      path: '/settings/brands'
      fullPath: '/settings/brands/'
      preLoaderRoute: typeof ShellSettingsBrandsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellTransactionsRoute: typeof ShellTransactionsRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellBatchesBatchIdRoute: typeof ShellBatchesBatchIdRoute
  ShellBrandBrandIdRoute: typeof ShellBrandBrandIdRoute
  ShellMerchantMerchantIdRoute: typeof ShellMerchantMerchantIdRoute
  ShellOwnedOwnedItemIdRoute: typeof ShellOwnedOwnedItemIdRoute
  ShellReceiptReceiptIdRoute: typeof ShellReceiptReceiptIdRoute
  ShellReviewMonthlyRoute: typeof ShellReviewMonthlyRoute
  ShellReviewYearlyRoute: typeof ShellReviewYearlyRoute
  ShellWishWishIdRoute: typeof ShellWishWishIdRoute
  ShellBatchesIndexRoute: typeof ShellBatchesIndexRoute
  ShellInsightsIndexRoute: typeof ShellInsightsIndexRoute
  ShellOwnedIndexRoute: typeof ShellOwnedIndexRoute
  ShellSettingsIndexRoute: typeof ShellSettingsIndexRoute
  ShellWishIndexRoute: typeof ShellWishIndexRoute
  ShellSettingsBrandsIndexRoute: typeof ShellSettingsBrandsIndexRoute
  ShellSettingsProductsIndexRoute: typeof ShellSettingsProductsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellTransactionsRoute: ShellTransactionsRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellBatchesBatchIdRoute: ShellBatchesBatchIdRoute,
  ShellBrandBrandIdRoute: ShellBrandBrandIdRoute,
  ShellMerchantMerchantIdRoute: ShellMerchantMerchantIdRoute,
  ShellOwnedOwnedItemIdRoute: ShellOwnedOwnedItemIdRoute,
  ShellReceiptReceiptIdRoute: ShellReceiptReceiptIdRoute,
  ShellReviewMonthlyRoute: ShellReviewMonthlyRoute,
  ShellReviewYearlyRoute: ShellReviewYearlyRoute,
  ShellWishWishIdRoute: ShellWishWishIdRoute,
  ShellBatchesIndexRoute: ShellBatchesIndexRoute,
  ShellInsightsIndexRoute: ShellInsightsIndexRoute,
  ShellOwnedIndexRoute: ShellOwnedIndexRoute,
  ShellSettingsIndexRoute: ShellSettingsIndexRoute,
  ShellWishIndexRoute: ShellWishIndexRoute,
  ShellSettingsBrandsIndexRoute: ShellSettingsBrandsIndexRoute,
  ShellSettingsProductsIndexRoute: ShellSettingsProductsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AddRoute: AddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
